codecov:
  token: "b6eae9ce-30f4-45fa-aa39-26e13f73d6ec"
  bot: "codecov-io"
  ci:
    - "travis.org"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
#    coverage:
#      precision: 1
#      round: down
#      range: "50...80"
#      status:
#        project:
#          default:
#            # Do not fail PRs if the code coverage drops.
#            target: 0%
#            threshold: null
#            base: auto